### ISSUE TITLE
Let Ember awards clean up after themselves

### ISSUE THREAD

**Issue by Maldor** [LaughLax/icarus5#74]
Messages stating ember was awarded should clean themselves up after a time, not immediately but certainly shouldn't hang around for ages.

**Comment by Maldor** [comment]
Confusion happened. Ephemeral messages were deemed ok

**Comment by LaughLax** [comment]
Reopening; `/bank award` should post to the new House Mop Bucket channel (instead of Heads of House) and `/bank give` should be non-ephemeral but clean up after itself. `/bank award` should also post a local that cleans up after itself.

While we're at it: people giving ember to Icarus should ping Discord Manager, not Owner.
